// ===== Game Content =====
// level: 1 = Sprout, 2 = Explorer, 3 = Star Reader
// Higher levels can still draw a few items from the level below for variety.

const SIGHT_WORDS = [
  // Level 1
  { word: 'the', hint: 'Most common word!', emoji: '👑', level: 1 },
  { word: 'and', hint: 'Joins two things', emoji: '🔗', level: 1 },
  { word: 'a', hint: 'One of something', emoji: '1️⃣', level: 1 },
  { word: 'to', hint: 'Going somewhere', emoji: '➡️', level: 1 },
  { word: 'is', hint: 'Something exists', emoji: '✅', level: 1 },
  { word: 'in', hint: 'Inside something', emoji: '📦', level: 1 },
  { word: 'it', hint: 'A thing nearby', emoji: '👉', level: 1 },
  { word: 'you', hint: 'The person reading!', emoji: '🫵', level: 1 },
  { word: 'he', hint: 'A boy or man', emoji: '👦', level: 1 },
  { word: 'she', hint: 'A girl or woman', emoji: '👧', level: 1 },
  { word: 'was', hint: 'Happened before', emoji: '⏮️', level: 1 },
  { word: 'are', hint: 'More than one is', emoji: '🟰', level: 1 },
  { word: 'at', hint: 'A place or time', emoji: '📍', level: 1 },
  { word: 'be', hint: 'To exist', emoji: '💫', level: 1 },
  { word: 'this', hint: 'Right here!', emoji: '👇', level: 1 },
  { word: 'have', hint: 'Own something', emoji: '🤲', level: 1 },
  { word: 'from', hint: 'Where it started', emoji: '🚩', level: 1 },
  { word: 'or', hint: 'A choice', emoji: '🔀', level: 1 },
  { word: 'one', hint: 'The number 1', emoji: '1️⃣', level: 1 },
  { word: 'had', hint: 'Owned before', emoji: '🕰️', level: 1 },
  { word: 'by', hint: 'Next to or made by', emoji: '📐', level: 1 },
  { word: 'but', hint: 'However', emoji: '⚠️', level: 1 },
  { word: 'not', hint: 'No, opposite', emoji: '🚫', level: 1 },
  { word: 'all', hint: 'Every single one', emoji: '🌍', level: 1 },
  { word: 'were', hint: 'They existed', emoji: '⏮️', level: 1 },
  { word: 'can', hint: 'Able to do it', emoji: '💪', level: 1 },
  { word: 'said', hint: 'Spoke words', emoji: '💬', level: 1 },
  { word: 'see', hint: 'Use your eyes', emoji: '👀', level: 1 },
  { word: 'get', hint: 'Go and get it', emoji: '🤝', level: 1 },
  { word: 'like', hint: 'To enjoy', emoji: '❤️', level: 1 },
  // Level 2
  { word: 'what', hint: 'Asking about a thing', emoji: '❓', level: 2 },
  { word: 'when', hint: 'Asking about time', emoji: '⏰', level: 2 },
  { word: 'where', hint: 'Asking about a place', emoji: '📍', level: 2 },
  { word: 'who', hint: 'Asking about a person', emoji: '🙋', level: 2 },
  { word: 'why', hint: 'Asking for a reason', emoji: '🤔', level: 2 },
  { word: 'how', hint: 'Asking the way to do it', emoji: '🛠️', level: 2 },
  { word: 'there', hint: 'In that place', emoji: '👉', level: 2 },
  { word: 'then', hint: 'After that', emoji: '➡️', level: 2 },
  { word: 'them', hint: 'Those people', emoji: '👥', level: 2 },
  { word: 'some', hint: 'A few of something', emoji: '🍬', level: 2 },
  { word: 'come', hint: 'Move closer', emoji: '🤗', level: 2 },
  { word: 'want', hint: 'Wish to have it', emoji: '🌟', level: 2 },
  { word: 'went', hint: 'Moved away before', emoji: '🚶', level: 2 },
  { word: 'saw', hint: 'Used your eyes before', emoji: '👀', level: 2 },
  { word: 'out', hint: 'Not inside', emoji: '🚪', level: 2 },
  { word: 'look', hint: 'Use your eyes now', emoji: '🔍', level: 2 },
  { word: 'little', hint: 'Very small', emoji: '🐜', level: 2 },
  { word: 'make', hint: 'Build or create it', emoji: '🏗️', level: 2 },
  { word: 'take', hint: 'Pick it up and keep it', emoji: '🤲', level: 2 },
  { word: 'give', hint: 'Hand it to someone', emoji: '🎁', level: 2 },
  { word: 'know', hint: 'Have it in your head', emoji: '🧠', level: 2 },
  { word: 'think', hint: 'Use your brain', emoji: '💭', level: 2 },
  { word: 'very', hint: 'A lot, really', emoji: '💯', level: 2 },
  { word: 'again', hint: 'One more time', emoji: '🔁', level: 2 },
  { word: 'away', hint: 'Far from here', emoji: '🏃', level: 2 },
  { word: 'could', hint: 'Was able to', emoji: '💪', level: 2 },
  { word: 'would', hint: 'Might do it', emoji: '🤝', level: 2 },
  { word: 'right', hint: 'Correct, or not left', emoji: '✅', level: 2 },
  { word: 'jump', hint: 'Push off the ground', emoji: '🦘', level: 2 },
  { word: 'help', hint: 'Do something for someone', emoji: '🆘', level: 2 },
  { word: 'find', hint: 'Look until you see it', emoji: '🗺️', level: 2 },
  { word: 'funny', hint: 'Makes you laugh', emoji: '😂', level: 2 },
  { word: 'good', hint: 'The opposite of bad', emoji: '👍', level: 2 },
  { word: 'new', hint: 'Not old', emoji: '✨', level: 2 },
  { word: 'over', hint: 'Above or across', emoji: '🌉', level: 2 },
  { word: 'under', hint: 'Below something', emoji: '⬇️', level: 2 },
  { word: 'after', hint: 'Later than', emoji: '🕐', level: 2 },
  { word: 'first', hint: 'Number one in line', emoji: '🥇', level: 2 },
  { word: 'many', hint: 'A big number of things', emoji: '🔢', level: 2 },
  { word: 'down', hint: 'Toward the ground', emoji: '⤵️', level: 2 },
  // Level 3
  { word: 'because', hint: 'Gives the reason', emoji: '💡', level: 3 },
  { word: 'before', hint: 'Earlier than', emoji: '⏪', level: 3 },
  { word: 'together', hint: 'With each other', emoji: '👫', level: 3 },
  { word: 'friend', hint: 'Someone you like a lot', emoji: '🧑‍🤝‍🧑', level: 3 },
  { word: 'people', hint: 'Lots of persons', emoji: '👨‍👩‍👧‍👦', level: 3 },
  { word: 'water', hint: 'You drink it', emoji: '💧', level: 3 },
  { word: 'laugh', hint: 'Ha ha ha!', emoji: '🤣', level: 3 },
  { word: 'thought', hint: 'An idea in your head', emoji: '💭', level: 3 },
  { word: 'through', hint: 'In one side, out the other', emoji: '🚇', level: 3 },
  { word: 'enough', hint: 'As much as you need', emoji: '🈵', level: 3 },
  { word: 'once', hint: 'One time only', emoji: '1️⃣', level: 3 },
  { word: 'only', hint: 'Just this, nothing else', emoji: '☝️', level: 3 },
  { word: 'always', hint: 'Every single time', emoji: '♾️', level: 3 },
  { word: 'never', hint: 'Not even one time', emoji: '🚫', level: 3 },
  { word: 'around', hint: 'In a circle', emoji: '🔄', level: 3 },
  { word: 'better', hint: 'More good', emoji: '📈', level: 3 },
  { word: 'carry', hint: 'Hold it while you walk', emoji: '🎒', level: 3 },
  { word: 'clean', hint: 'Not dirty', emoji: '🧼', level: 3 },
  { word: 'draw', hint: 'Make a picture', emoji: '🖍️', level: 3 },
  { word: 'drink', hint: 'Swallow a liquid', emoji: '🥤', level: 3 },
  { word: 'eight', hint: 'The number 8', emoji: '8️⃣', level: 3 },
  { word: 'grow', hint: 'Get bigger', emoji: '🌱', level: 3 },
  { word: 'hold', hint: 'Keep it in your hands', emoji: '🤲', level: 3 },
  { word: 'kind', hint: 'Nice to others', emoji: '💗', level: 3 },
  { word: 'light', hint: 'Not dark, or not heavy', emoji: '💡', level: 3 },
  { word: 'myself', hint: 'Me, on my own', emoji: '🪞', level: 3 },
  { word: 'shall', hint: 'Will do it', emoji: '📜', level: 3 },
  { word: 'show', hint: 'Let someone see it', emoji: '🎭', level: 3 },
  { word: 'today', hint: 'This very day', emoji: '📅', level: 3 },
  { word: 'warm', hint: 'A little bit hot', emoji: '☀️', level: 3 },
];

const PHONICS_WORDS = [
  // Level 1
  { word: 'cat', chunks: ['c', 'at'], emoji: '🐱', level: 1 },
  { word: 'dog', chunks: ['d', 'og'], emoji: '🐶', level: 1 },
  { word: 'sun', chunks: ['s', 'un'], emoji: '☀️', level: 1 },
  { word: 'hat', chunks: ['h', 'at'], emoji: '🎩', level: 1 },
  { word: 'big', chunks: ['b', 'ig'], emoji: '🐘', level: 1 },
  { word: 'red', chunks: ['r', 'ed'], emoji: '🔴', level: 1 },
  { word: 'cup', chunks: ['c', 'up'], emoji: '☕', level: 1 },
  { word: 'pen', chunks: ['p', 'en'], emoji: '🖊️', level: 1 },
  { word: 'hop', chunks: ['h', 'op'], emoji: '🐇', level: 1 },
  { word: 'mud', chunks: ['m', 'ud'], emoji: '🟤', level: 1 },
  { word: 'ship', chunks: ['sh', 'ip'], emoji: '🚢', level: 1 },
  { word: 'chin', chunks: ['ch', 'in'], emoji: '🙂', level: 1 },
  { word: 'thin', chunks: ['th', 'in'], emoji: '📏', level: 1 },
  { word: 'when', chunks: ['wh', 'en'], emoji: '⏰', level: 1 },
  { word: 'frog', chunks: ['fr', 'og'], emoji: '🐸', level: 1 },
  { word: 'clap', chunks: ['cl', 'ap'], emoji: '👏', level: 1 },
  { word: 'snap', chunks: ['sn', 'ap'], emoji: '🫰', level: 1 },
  { word: 'trip', chunks: ['tr', 'ip'], emoji: '🚗', level: 1 },
  { word: 'blue', chunks: ['bl', 'ue'], emoji: '🔵', level: 1 },
  { word: 'play', chunks: ['pl', 'ay'], emoji: '🎈', level: 1 },
  { word: 'cake', chunks: ['c', 'a', 'ke'], emoji: '🍰', level: 1 },
  { word: 'bike', chunks: ['b', 'i', 'ke'], emoji: '🚲', level: 1 },
  { word: 'home', chunks: ['h', 'o', 'me'], emoji: '🏠', level: 1 },
  { word: 'smile', chunks: ['sm', 'i', 'le'], emoji: '😄', level: 1 },
  // Level 2 — magic-e
  { word: 'gate', chunks: ['g', 'a', 'te'], emoji: '🚧', level: 2 },
  { word: 'kite', chunks: ['k', 'i', 'te'], emoji: '🪁', level: 2 },
  { word: 'note', chunks: ['n', 'o', 'te'], emoji: '🎵', level: 2 },
  { word: 'cube', chunks: ['c', 'u', 'be'], emoji: '🧊', level: 2 },
  { word: 'wave', chunks: ['w', 'a', 've'], emoji: '🌊', level: 2 },
  { word: 'five', chunks: ['f', 'i', 've'], emoji: '5️⃣', level: 2 },
  { word: 'rose', chunks: ['r', 'o', 'se'], emoji: '🌹', level: 2 },
  // Level 2 — vowel teams
  { word: 'rain', chunks: ['r', 'ai', 'n'], emoji: '🌧️', level: 2 },
  { word: 'boat', chunks: ['b', 'oa', 't'], emoji: '⛵', level: 2 },
  { word: 'seed', chunks: ['s', 'ee', 'd'], emoji: '🌱', level: 2 },
  { word: 'moon', chunks: ['m', 'oo', 'n'], emoji: '🌕', level: 2 },
  { word: 'team', chunks: ['t', 'ea', 'm'], emoji: '⚽', level: 2 },
  { word: 'coat', chunks: ['c', 'oa', 't'], emoji: '🧥', level: 2 },
  { word: 'night', chunks: ['n', 'igh', 't'], emoji: '🌃', level: 2 },
  { word: 'light', chunks: ['l', 'igh', 't'], emoji: '💡', level: 2 },
  { word: 'snail', chunks: ['sn', 'ai', 'l'], emoji: '🐌', level: 2 },
  { word: 'sheep', chunks: ['sh', 'ee', 'p'], emoji: '🐑', level: 2 },
  { word: 'beach', chunks: ['b', 'ea', 'ch'], emoji: '🏖️', level: 2 },
  { word: 'spoon', chunks: ['sp', 'oo', 'n'], emoji: '🥄', level: 2 },
  // Level 2 — r-controlled
  { word: 'car', chunks: ['c', 'ar'], emoji: '🚗', level: 2 },
  { word: 'star', chunks: ['st', 'ar'], emoji: '⭐', level: 2 },
  { word: 'bird', chunks: ['b', 'ir', 'd'], emoji: '🐦', level: 2 },
  { word: 'corn', chunks: ['c', 'or', 'n'], emoji: '🌽', level: 2 },
  { word: 'shark', chunks: ['sh', 'ar', 'k'], emoji: '🦈', level: 2 },
  // Level 3 — syllable chunking
  { word: 'rabbit', chunks: ['rab', 'bit'], emoji: '🐰', level: 3 },
  { word: 'sunset', chunks: ['sun', 'set'], emoji: '🌇', level: 3 },
  { word: 'pancake', chunks: ['pan', 'cake'], emoji: '🥞', level: 3 },
  { word: 'rainbow', chunks: ['rain', 'bow'], emoji: '🌈', level: 3 },
  { word: 'popcorn', chunks: ['pop', 'corn'], emoji: '🍿', level: 3 },
  { word: 'cupcake', chunks: ['cup', 'cake'], emoji: '🧁', level: 3 },
  { word: 'spider', chunks: ['spi', 'der'], emoji: '🕷️', level: 3 },
  { word: 'tiger', chunks: ['ti', 'ger'], emoji: '🐯', level: 3 },
  { word: 'dragon', chunks: ['drag', 'on'], emoji: '🐉', level: 3 },
  { word: 'monster', chunks: ['mon', 'ster'], emoji: '👾', level: 3 },
  { word: 'butterfly', chunks: ['but', 'ter', 'fly'], emoji: '🦋', level: 3 },
  { word: 'dinosaur', chunks: ['di', 'no', 'saur'], emoji: '🦕', level: 3 },
  { word: 'elephant', chunks: ['el', 'e', 'phant'], emoji: '🐘', level: 3 },
  { word: 'umbrella', chunks: ['um', 'brel', 'la'], emoji: '☂️', level: 3 },
  { word: 'fantastic', chunks: ['fan', 'tas', 'tic'], emoji: '🎉', level: 3 },
  { word: 'adventure', chunks: ['ad', 'ven', 'ture'], emoji: '🗺️', level: 3 },
];

const SENTENCES = [
  // Level 1
  { text: 'The cat sat on the mat.', emoji: '🐱', level: 1 },
  { text: 'A big red dog ran fast.', emoji: '🐶', level: 1 },
  { text: 'She can see the blue sky.', emoji: '🌤️', level: 1 },
  { text: 'He had a hat and a bag.', emoji: '🎩', level: 1 },
  { text: 'The sun is hot today.', emoji: '☀️', level: 1 },
  { text: 'I like to eat cake.', emoji: '🍰', level: 1 },
  { text: 'We can play and have fun.', emoji: '🎈', level: 1 },
  { text: 'The frog can hop and jump.', emoji: '🐸', level: 1 },
  { text: 'My dog likes to run and play.', emoji: '🐕', level: 1 },
  { text: 'She said the bird can fly.', emoji: '🐦', level: 1 },
  { text: 'He is not at home today.', emoji: '🏠', level: 1 },
  { text: 'All the kids like to read.', emoji: '📚', level: 1 },
  { text: 'Can you see the big ship?', emoji: '🚢', level: 1 },
  { text: 'The red bike is by the tree.', emoji: '🚲', level: 1 },
  { text: 'You are a great reader!', emoji: '🌟', level: 1 },
  // Level 2
  { text: 'The little bird made a nest in the tall tree.', emoji: '🐦', level: 2 },
  { text: 'We went to the beach and found three white shells.', emoji: '🐚', level: 2 },
  { text: 'My friend has a green kite that flies very high.', emoji: '🪁', level: 2 },
  { text: 'The moon and stars come out when it is night.', emoji: '🌙', level: 2 },
  { text: 'She put on her red boots and jumped in puddles.', emoji: '👢', level: 2 },
  { text: 'Dad made pancakes for breakfast on Sunday morning.', emoji: '🥞', level: 2 },
  { text: 'The brave knight rode his horse to the old castle.', emoji: '🏰', level: 2 },
  { text: 'A rainbow came out after the rain stopped falling.', emoji: '🌈', level: 2 },
  { text: 'The children played hide and seek in the garden.', emoji: '🌳', level: 2 },
  { text: 'I read a funny book about a dog who could sing.', emoji: '📖', level: 2 },
  { text: 'The train goes fast through the dark tunnel.', emoji: '🚂', level: 2 },
  { text: 'We planted seeds and watered them every day.', emoji: '🌱', level: 2 },
  { text: 'The baby elephant splashed water with its trunk.', emoji: '🐘', level: 2 },
  { text: 'Grandma baked cookies and the house smelled sweet.', emoji: '🍪', level: 2 },
  { text: 'Look at the snowman with a carrot for a nose!', emoji: '⛄', level: 2 },
  // Level 3
  { text: 'Yesterday we visited the museum and saw dinosaur bones that were millions of years old.', emoji: '🦕', level: 3 },
  { text: 'If you listen carefully, you can hear the owl hooting in the forest at night.', emoji: '🦉', level: 3 },
  { text: 'The astronaut floated inside the spaceship and looked down at our beautiful blue planet.', emoji: '🚀', level: 3 },
  { text: 'Although it was raining, the children decided to play outside with their umbrellas.', emoji: '☔', level: 3 },
  { text: 'My little brother laughed so hard that milk almost came out of his nose.', emoji: '🥛', level: 3 },
  { text: 'The clever fox waited quietly behind the bushes until the rabbit hopped away.', emoji: '🦊', level: 3 },
  { text: 'Before you go to sleep, remember to brush your teeth and choose a bedtime story.', emoji: '🪥', level: 3 },
  { text: 'The dragon was not scary at all; it just wanted someone to share its treasure with.', emoji: '🐉', level: 3 },
  { text: 'When summer comes, we will swim in the lake and eat ice cream by the shore.', emoji: '🍦', level: 3 },
  { text: 'The strawberry plants in our garden grew so many berries that we made jam.', emoji: '🍓', level: 3 },
  { text: 'Everyone clapped when the magician pulled a fluffy white rabbit out of his hat.', emoji: '🎩', level: 3 },
  { text: 'The library is my favourite place, because every book is a new adventure.', emoji: '📚', level: 3 },
];

const STORIES = [
  {
    title: 'The Lost Kitten', emoji: '🐱', level: 2,
    pages: [
      { text: 'Mia heard a tiny sound outside the door.', emoji: '🚪' },
      { text: 'It was a small grey kitten with big green eyes.', emoji: '🐱' },
      { text: 'The kitten was cold and hungry.', emoji: '🥶' },
      { text: 'Mia gave it warm milk and a soft blanket.', emoji: '🥛' },
      { text: 'Now the kitten sleeps on her bed every night.', emoji: '😴' },
    ],
    questions: [
      { q: 'What did Mia hear outside the door?', options: ['A tiny sound', 'Loud music', 'A car horn'], answer: 0 },
      { q: 'What did Mia give the kitten?', options: ['A toy car', 'Warm milk and a blanket', 'A book'], answer: 1 },
    ],
  },
  {
    title: 'Oskar and the Dragon', emoji: '🐉', level: 2,
    pages: [
      { text: 'Oskar found a green egg in the forest.', emoji: '🥚' },
      { text: 'He kept it warm under his woolly hat.', emoji: '🧢' },
      { text: 'One morning the egg cracked open.', emoji: '💥' },
      { text: 'A baby dragon popped out and sneezed a tiny flame.', emoji: '🔥' },
      { text: 'Oskar named him Spark, and they became best friends.', emoji: '🐉' },
    ],
    questions: [
      { q: 'Where did Oskar find the egg?', options: ['In the forest', 'At school', 'In the sea'], answer: 0 },
      { q: 'What did Oskar name the dragon?', options: ['Flame', 'Spark', 'Smoky'], answer: 1 },
    ],
  },
  {
    title: 'The Strawberry Garden', emoji: '🍓', level: 3,
    pages: [
      { text: 'In spring, Mia planted ten small strawberry plants in the garden.', emoji: '🌱' },
      { text: 'Every morning she watered them before school.', emoji: '🚿' },
      { text: 'One day she saw something red hiding under the green leaves.', emoji: '👀' },
      { text: 'The strawberries were ripe, sweet, and ready to pick!', emoji: '🍓' },
      { text: 'Mia shared them with Oskar, but she kept the biggest one for herself.', emoji: '😋' },
    ],
    questions: [
      { q: 'When did Mia water the plants?', options: ['After dinner', 'Before school', 'At night'], answer: 1 },
      { q: 'Who got the biggest strawberry?', options: ['Oskar', 'Mum', 'Mia'], answer: 2 },
    ],
  },
  {
    title: 'A Trip to the Moon', emoji: '🚀', level: 3,
    pages: [
      { text: 'Oskar built a rocket out of boxes, tape, and one shiny button.', emoji: '📦' },
      { text: 'He counted down: three, two, one... blast off!', emoji: '🚀' },
      { text: 'The rocket zoomed past the clouds and into the starry sky.', emoji: '🌌' },
      { text: 'On the moon, he bounced higher than a kangaroo.', emoji: '🦘' },
      { text: 'He flew home in time for dinner, with moon dust still on his shoes.', emoji: '🌕' },
    ],
    questions: [
      { q: 'What was the rocket made of?', options: ['Metal and glass', 'Boxes, tape, and a button', 'Wood and rope'], answer: 1 },
      { q: 'What was still on his shoes at dinner?', options: ['Moon dust', 'Mud', 'Sand'], answer: 0 },
    ],
  },
  {
    title: 'The Rainy Day Fort', emoji: '🌧️', level: 3,
    pages: [
      { text: 'It rained all day, so Mia and Oskar could not play outside.', emoji: '🌧️' },
      { text: 'They built a huge fort with blankets, pillows, and chairs.', emoji: '🏰' },
      { text: 'Inside the fort they read books with a torch.', emoji: '🔦' },
      { text: 'They ate biscuits and told each other silly jokes.', emoji: '🍪' },
      { text: 'When the sun came out, they did not even notice!', emoji: '☀️' },
    ],
    questions: [
      { q: 'Why did they stay inside?', options: ['It was snowing', 'It rained all day', 'It was too hot'], answer: 1 },
      { q: 'What did they use to read in the fort?', options: ['A torch', 'A candle', 'A lamp'], answer: 0 },
    ],
  },
];

const CLOZE = [
  // Level 1
  { text: 'The ___ is shining in the sky.', answer: 'sun', options: ['sun', 'run', 'fun'], emoji: '☀️', level: 1 },
  { text: 'The cat drinks ___ from a bowl.', answer: 'milk', options: ['milk', 'mud', 'moon'], emoji: '🐱', level: 1 },
  { text: 'I put on my ___ when it rains.', answer: 'coat', options: ['coat', 'cake', 'coin'], emoji: '🧥', level: 1 },
  { text: 'A frog can ___ very high.', answer: 'jump', options: ['jump', 'sleep', 'sing'], emoji: '🐸', level: 1 },
  { text: 'We sleep in a ___ at night.', answer: 'bed', options: ['bed', 'bus', 'box'], emoji: '🛏️', level: 1 },
  // Level 2
  { text: 'The bird built a ___ in the tree.', answer: 'nest', options: ['nest', 'net', 'tent'], emoji: '🐦', level: 2 },
  { text: 'We use an ___ when it is raining.', answer: 'umbrella', options: ['umbrella', 'elephant', 'orange'], emoji: '☔', level: 2 },
  { text: 'The ___ swims deep in the sea.', answer: 'shark', options: ['shark', 'sheep', 'shirt'], emoji: '🦈', level: 2 },
  { text: 'At night the ___ glows in the dark sky.', answer: 'moon', options: ['moon', 'spoon', 'mouse'], emoji: '🌕', level: 2 },
  { text: 'She ate a sweet red ___ from the garden.', answer: 'strawberry', options: ['strawberry', 'stone', 'spider'], emoji: '🍓', level: 2 },
  // Level 3
  { text: 'The knight was very ___ and fought the dragon.', answer: 'brave', options: ['brave', 'sleepy', 'hungry'], emoji: '⚔️', level: 3 },
  { text: 'We could not play outside ___ it was raining.', answer: 'because', options: ['because', 'before', 'behind'], emoji: '🌧️', level: 3 },
  { text: 'The magician made the rabbit ___ into thin air.', answer: 'disappear', options: ['disappear', 'dance', 'dinner'], emoji: '🎩', level: 3 },
  { text: 'An ___ flies a spaceship far above the Earth.', answer: 'astronaut', options: ['astronaut', 'artist', 'animal'], emoji: '🚀', level: 3 },
  { text: 'Reading books is a wonderful ___ every single day.', answer: 'adventure', options: ['adventure', 'accident', 'afternoon'], emoji: '📚', level: 3 },
];

const RHYMES = [
  { prompt: 'cat', answer: 'hat', options: ['hat', 'dog', 'cup'], emoji: '🐱', level: 1 },
  { prompt: 'frog', answer: 'log', options: ['log', 'leaf', 'lake'], emoji: '🐸', level: 1 },
  { prompt: 'bed', answer: 'red', options: ['red', 'blue', 'bad'], emoji: '🛏️', level: 1 },
  { prompt: 'bee', answer: 'tree', options: ['tree', 'bug', 'ant'], emoji: '🐝', level: 1 },
  { prompt: 'mouse', answer: 'house', options: ['house', 'hole', 'cat'], emoji: '🐭', level: 1 },
  { prompt: 'moon', answer: 'spoon', options: ['spoon', 'star', 'sun'], emoji: '🌕', level: 2 },
  { prompt: 'cake', answer: 'snake', options: ['snake', 'cook', 'kite'], emoji: '🍰', level: 2 },
  { prompt: 'star', answer: 'car', options: ['car', 'ship', 'sky'], emoji: '⭐', level: 2 },
  { prompt: 'goat', answer: 'boat', options: ['boat', 'cow', 'gate'], emoji: '🐐', level: 2 },
  { prompt: 'night', answer: 'light', options: ['light', 'dark', 'note'], emoji: '🌃', level: 2 },
  { prompt: 'rain', answer: 'train', options: ['train', 'cloud', 'ran'], emoji: '🌧️', level: 3 },
  { prompt: 'king', answer: 'ring', options: ['ring', 'crown', 'kind'], emoji: '👑', level: 3 },
];

const STICKER_SETS = {
  animals: ['🦊', '🐢', '🦄', '🐙', '🦁', '🐼', '🦉', '🐬'],
  space: ['🪐', '🌟', '🛸', '☄️', '👽', '🌙', '🌌', '🚀'],
  treats: ['🧁', '🍭', '🍩', '🍉', '🍦', '🍪', '🍓', '🍰'],
  magic: ['🧚', '🦄', '🌈', '✨', '🔮', '🪄', '👑', '💎'],
};
